### ISSUE TITLE
CONTACT US + NOMINATE PAGE - adjustment

### ISSUE THREAD

**Issue by Fatimbit** [Software-For-Love/humans#45]
change animation: try making all moving content smaller and recording what it looks like + try making a version of it where the content that is currently moving in the animation is static and document what that looks like as well (take a screenshot or something similar). Once we have recordings/pictures of what it would look like both ways we can move forward with whichever version is approved

UPDATE: animation must be changed to static images

**Comment by jkokkat** [comment]
![C15ACDAB-E680-4B31-A4DD-2A6290554BDD_1_105_c](https://user-images.githubusercontent.com/55165117/152653533-4b1f5778-f089-4570-ad6e-9ce875137e52.jpeg)

**Comment by jkokkat** [comment]
![7A91022A-6B44-43CF-A471-134A612D1300_1_105_c](https://user-images.githubusercontent.com/55165117/152653679-8bfd913c-d075-49f0-8277-b0e5a1ca6bb2.jpeg)

**Comment by jkokkat** [comment]
![FCA8C25B-D04D-4C16-9EF0-BE91A9555631_1_105_c](https://user-images.githubusercontent.com/55165117/152653695-3928dba4-4a91-481d-8ca2-07794371a1b2.jpeg)

**Comment by jkokkat** [comment]
https://drive.google.com/file/d/1xH_U12caQYyTt7_VDm4mA48w2NeAF7_P/view?usp=sharing
This is the video of the moving animation.

**Comment by Fatimbit** [comment]
Hey Jasmine :) Good work so far! Could you try to make it smaller (approximately so that the bottom of the box would be above the checkbox and SUBMIT button) because I think it's still too big, unfortunately
